FROM node:20-docker
WORKDIR /app
COPY worker/package*json ./
RUN npm install
COPY worker ./
COPY primary/dist/prismadb.js ./primary/dist/prismadb.js
RUN npm install -g typescript
RUN npx tsc 
CMD [ "node" , "dist/consumer.js" ]

